# Tomcat
server.port: 11111
# Logging level (TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF)

spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

logging:
    level:
        org.hibernate: WARN
        org.springframework: WARN
    file: githubApi.log
# Spring settings
spring:
    profiles.active: dev
    resources.cache-period: 0
    http.multipart:
        max-file-size: 10MB
        max-request-size: 10MB
        resolve-lazily: true
    datasource:
        url: jdbc:mysql://localhost:3306/sdd?characterEncoding=utf8&useSSL=true
        username: root
        password: root
    jpa:
        show-sql: false
        hibernate:
            # Hibernate DDL  auto: create, create-drop, update, validate
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            properties:
                hibernate.dialect: org.hibernate.dialect.MySQL5Dialect